<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="bl3175, cw3747, lg3450, yw4662" />

<meta name="date" content="2025-11-27" />

<title>P8105_final_Alzheimei</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Cognitive Decline in the U.S.</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">
    <span class="fa fa-whiteboard fa-semibold fa-house"></span>
     
  </a>
</li>
<li>
  <a href="data_source.html">Data Analysis</a>
</li>
<li>
  <a href="demographic_analysis.html">Demographic Analysis</a>
</li>
<li>
  <a href="geographic_analysis.html">Geographic Analysis</a>
</li>
<li>
  <a href="interactive_maps.html">Interactive Map</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="about_us.html">About Us</a>
</li>
<li>
  <a href="https://github.com/WenYe2683/p8105_fp_alzheimer">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-envelope fa-lg"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mailto:bl3175@cumc.columbia.edu">Bing Li</a>
    </li>
    <li>
      <a href="mailto:cw3747@cumc.columbia.edu">Chuhan Wang</a>
    </li>
    <li>
      <a href="mailto:lg3450@cumc.columbia.edu">Luyun Ge</a>
    </li>
    <li>
      <a href="mailto:yw4662@cumc.columbia.edu">Ye Wen</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">P8105_final_Alzheimei</h1>
<h4 class="author">bl3175, cw3747, lg3450, yw4662</h4>
<h4 class="date">2025-11-27</h4>

</div>


<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<pre class="r"><code>library(patchwork)
library(scales)</code></pre>
<pre><code>## 
## Attaching package: &#39;scales&#39;
## 
## The following object is masked from &#39;package:purrr&#39;:
## 
##     discard
## 
## The following object is masked from &#39;package:readr&#39;:
## 
##     col_factor</code></pre>
<pre class="r"><code>library(dplyr)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = &quot;90%&quot;
)

theme_set(theme_minimal() + theme(legend.position = &quot;bottom&quot;))

options(
  ggplot2.continuous.colour = &quot;viridis&quot;,
  ggplot2.continuous.fill = &quot;viridis&quot;
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d</code></pre>
<div id="data-import" class="section level2">
<h2>Data Import</h2>
<pre class="r"><code>raw_az_data &lt;- read.csv(&quot;data/2015-2022 Alzheimer Data.csv&quot;) |&gt;
  janitor::clean_names()</code></pre>
<pre><code>## Warning in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,
## : EOF within quoted string</code></pre>
<pre class="r"><code>raw_az_data &lt;- raw_az_data[-nrow(raw_az_data), ]</code></pre>
<pre class="r"><code>az_clean &lt;- raw_az_data |&gt;
  filter(
    !is.na(data_value),
    !is.na(year_start),
    !is.na(location_abbr)
  )</code></pre>
</div>
<div id="descriptive" class="section level2">
<h2>Descriptive</h2>
<pre class="r"><code>az_clean |&gt;
  summarise(
    n_rows = n(),
    n_states = n_distinct(location_abbr),
    year_min = min(year_start),
    year_max = max(year_start),
    n_topics = n_distinct(topic),
    n_questions = n_distinct(question)
  )</code></pre>
<pre><code>##   n_rows n_states year_min year_max n_topics n_questions
## 1  32616       59     2015     2022       39          39</code></pre>
<p>We obtained data from the Centers for Disease Control and Prevention
(CDC) Alzheimer’s Disease and Healthy Aging Data, which are derived from
the Behavioral Risk Factor Surveillance System (BRFSS). After excluding
records with missing key identifiers, our analytic dataset contained
<strong>32,616</strong> observations from <strong>59</strong> states and
territories, covering survey years <strong>2015–2022</strong>. The
dataset includes <strong>39</strong> distinct topics and specific
questions on health status and health-related behaviors among
middle-aged and older adults.</p>
<p>For this study, we focused on BRFSS items whose topic was labeled
<strong>“cognitive decline”</strong> or <strong>“cognitive
impairment”</strong>. These items capture self-reported cognitive
problems among middle-aged and older adults, and we treat them as
Alzheimer’s-related cognitive indicators rather than clinically
confirmed Alzheimer’s disease.</p>
</div>
<div id="data-considering-alzheimer" class="section level2">
<h2>Data considering Alzheimer</h2>
<pre class="r"><code>library(stringr)

az_cog &lt;- az_clean |&gt;
  filter(
    str_detect(topic, regex(&quot;cognitive decline|cognitive impairment&quot;,
                            ignore_case = TRUE))
  )</code></pre>
<div id="sex-and-age-summary" class="section level3">
<h3>sex and age summary</h3>
<pre class="r"><code>az_cog_summary_base &lt;- az_cog |&gt;
  mutate(
    age_group = case_when(
      stratification_category1 == &quot;Age Group&quot; ~ stratification1,
      TRUE ~ &quot;Overall&quot;
    ),
    sex_group = case_when(
      stratification_category2 == &quot;Sex&quot; ~ stratification2,
      TRUE ~ &quot;Overall&quot;
    )
  )</code></pre>
</div>
<div id="state-age-sex-table" class="section level3">
<h3>state × age × sex table</h3>
<pre class="r"><code>az_cog_state_age_sex &lt;- az_cog_summary_base |&gt;
  group_by(
    location_abbr, location_desc,
    age_group,
    sex_group
  ) |&gt;
  summarise(
    n_obs = n(),
    mean_value = mean(data_value, na.rm = TRUE),
    .groups = &quot;drop&quot;
  ) |&gt;
  arrange(desc(mean_value))

az_cog_state_age_sex</code></pre>
<pre><code>## # A tibble: 448 × 6
##    location_abbr location_desc age_group         sex_group n_obs mean_value
##    &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;             &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
##  1 PR            Puerto Rico   50-64 years       Female        4       59.8
##  2 PR            Puerto Rico   50-64 years       Overall       8       58.2
##  3 PR            Puerto Rico   Overall           Male          4       54.5
##  4 PR            Puerto Rico   Overall           Overall       8       53.6
##  5 PR            Puerto Rico   Overall           Female        4       52.8
##  6 PR            Puerto Rico   65 years or older Overall       8       47.9
##  7 RI            Rhode Island  50-64 years       Female        4       47.2
##  8 OK            Oklahoma      50-64 years       Female        4       46.6
##  9 DE            Delaware      50-64 years       Female        4       46.1
## 10 PR            Puerto Rico   65 years or older Female        4       44.7
## # ℹ 438 more rows</code></pre>
</div>
<div id="top-10-states-2015-2016" class="section level3">
<h3>top 10 states (2015-2016)</h3>
<pre class="r"><code>az_cog_65_overall &lt;- az_cog_summary_base |&gt;
  filter(
    age_group == &quot;65 years or older&quot;,
    sex_group == &quot;Overall&quot;
  )

nrow(az_cog_65_overall)</code></pre>
<pre><code>## [1] 609</code></pre>
<pre class="r"><code>sort(unique(az_cog_65_overall$year_start))</code></pre>
<pre><code>## [1] 2015 2016</code></pre>
<p>The CDC Healthy Aging dataset covers survey years 2015–2022. For
topics coded as Cognitive Decline or Cognitive Impairment, data were
only available in 2015–2016; therefore, our Alzheimer’s-related analyses
are restricted to these two years.</p>
<pre class="r"><code>library(ggplot2)

az_cog_65_overall &lt;- az_cog_summary_base |&gt;
  filter(
    age_group == &quot;65 years or older&quot;,
    sex_group == &quot;Overall&quot;
  )

years_use &lt;- c(2015, 2016)

az_cog_65_overall_15_16 &lt;- az_cog_65_overall |&gt;
  filter(year_start %in% years_use)</code></pre>
<pre class="r"><code>top10_state_15_16 &lt;- az_cog_65_overall_15_16 |&gt;
  group_by(location_abbr, location_desc) |&gt;
  summarise(
    n_obs = n(),
    mean_15_16 = mean(data_value, na.rm = TRUE),
    .groups = &quot;drop&quot;
  ) |&gt;
  arrange(desc(mean_15_16)) |&gt;
  slice_head(n = 10)

top10_state_15_16</code></pre>
<pre><code>## # A tibble: 10 × 4
##    location_abbr location_desc  n_obs mean_15_16
##    &lt;chr&gt;         &lt;chr&gt;          &lt;int&gt;      &lt;dbl&gt;
##  1 PR            Puerto Rico        8       47.9
##  2 NRE           Northeast         30       33.6
##  3 OK            Oklahoma           8       31.5
##  4 MS            Mississippi       14       31.4
##  5 SOU           South             30       31.0
##  6 SD            South Dakota       8       30.9
##  7 MA            Massachusetts      5       30.8
##  8 AL            Alabama           14       30.2
##  9 AK            Alaska             7       29.8
## 10 SC            South Carolina    14       29.5</code></pre>
<p>Using data from 2015–2016, we ranked states and regions by the mean
prevalence of Alzheimer’s-related cognitive indicators among adults aged
65 years and older (all sexes combined). The highest burden was observed
in Puerto Rico (mean prevalence 47.9%), which was notably higher than
any U.S. state or region. The Northeast region ranked second (33.6%),
followed by Oklahoma (31.5%), Mississippi (31.4%), and the South region
as a whole (31.0%). The remaining states in the top ten—South Dakota,
Massachusetts, Alabama, Alaska, and South Carolina—all had mean
prevalences around 30%. Overall, these results suggest substantial
geographic variation in self-reported cognitive problems among older
adults, with several Southern states and Puerto Rico showing
particularly high levels.</p>
<p>The Top 10 list for 2015–2016 is different from the earlier
state–age–sex table because they summarize different things. The
state–age–sex table ranks specific subgroups (for example, women aged
50–64 in Puerto Rico), so it shows where the highest subgroup
prevalences occur. In contrast, the 2015–2016 Top 10 is based only on
adults aged 65+ with sexes combined, giving one value per state. This
ranking reflects overall burden in older adults, not the maximum value
in any age–sex subgroup, and provides useful context for later
stratified analyses or adjustment for potential confounders such as age,
sex, or region.</p>
</div>
</div>
<div id="distribution-difference" class="section level2">
<h2>Distribution Difference</h2>
<div id="prevelance-year" class="section level3">
<h3>prevelance ~ year</h3>
<pre class="r"><code>az_nat_65_overall &lt;- az_cog_65_overall |&gt;
  group_by(year = year_start) |&gt;
  summarise(
    mean_prev = mean(data_value, na.rm = TRUE),
    sd_prev   = sd(data_value, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

az_nat_65_overall |&gt;
  mutate(year = factor(year)) |&gt;
  ggplot(aes(x = year, y = mean_prev)) +
  geom_col() +
  labs(
    x = &quot;Year&quot;,
    y = &quot;Mean prevalence (%)&quot;,
    title = &quot;Alzheimer’s-related cognitive indicators among adults 65+, 2015–2016&quot;
  )</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/unnamed-chunk-11-1.png" width="90%" /></p>
<p>At the national level, the mean prevalence of Alzheimer’s-related
cognitive indicators among adults aged 65+ was very similar in 2015
(26.0%) and 2016 (25.8%). The small difference of 0.2 percentage points
is well within the between-state variation and does not suggest any
clear change over this two-year period.</p>
</div>
<div id="prevelance-age" class="section level3">
<h3>prevelance ~ age</h3>
<pre class="r"><code>az_age_desc &lt;- az_cog_summary_base |&gt;
  group_by(age_group) |&gt;
  summarise(
    n_obs      = n(),
    mean_value = mean(data_value, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

ggplot(az_age_desc,
       aes(x = age_group, y = mean_value)) +
  geom_col() +
  labs(
    x = &quot;Age group&quot;,
    y = &quot;Mean prevalence (%)&quot;,
    title = &quot;Alzheimer’s-related cognitive indicators by age group&quot;
  )</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/unnamed-chunk-12-1.png" width="90%" /></p>
<p>Across all cognitive items, the mean prevalence was about 31.8% among
adults aged 50–64 years and 25.8% among those aged 65 years or
older.</p>
</div>
<div id="prevelance-sex" class="section level3">
<h3>prevelance ~ sex</h3>
<pre class="r"><code>az_sex_desc &lt;- az_cog_summary_base |&gt;
  group_by(sex_group) |&gt;
  summarise(
    n_obs      = n(),
    mean_value = mean(data_value, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

ggplot(az_sex_desc,
       aes(x = sex_group, y = mean_value)) +
  geom_col() +
  labs(
    x = &quot;Sex&quot;,
    y = &quot;Mean prevalence (%)&quot;,
    title = &quot;Alzheimer’s-related cognitive indicators by sex&quot;
  )</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/unnamed-chunk-13-1.png" width="90%" /></p>
<p>Across all states and cognitive items in 2015–2016, women had a
higher mean prevalence of Alzheimer’s-related cognitive indicators than
men (30.9% vs 26.8%), suggesting a consistently greater reported
cognitive burden among female respondents.</p>
</div>
</div>
<div id="income-effects" class="section level2">
<h2>Income Effects</h2>
<div id="data-import-1" class="section level3">
<h3>data import</h3>
<pre class="r"><code>inc15 &lt;- read_csv(&quot;data/median income-2015.csv&quot;, skip = 1) |&gt;
  janitor::clean_names() |&gt;
  transmute(
    year = 2015,
    state_name = geographic_area_name,
    median_income = as.numeric(median_income_dollars_estimate_households)
  )</code></pre>
<pre><code>## New names:
## Rows: 830 Columns: 123
## ── Column specification
## ──────────────────────────────────────────────────────── Delimiter: &quot;,&quot; chr
## (83): Geography, Geographic Area Name, Total!!Estimate!!Households!!One ... dbl
## (39): Total!!Estimate!!Households, Total!!Margin of Error!!Households, M... lgl
## (1): ...123
## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
## Specify the column types or set `show_col_types = FALSE` to quiet this message.
## • `` -&gt; `...123`</code></pre>
<pre class="r"><code>inc16 &lt;- read_csv(&quot;data/median income-2016.csv&quot;, skip = 1) |&gt;
  janitor::clean_names() |&gt;
  transmute(
    year = 2016,
    state_name = geographic_area_name,
    median_income = as.numeric(median_income_dollars_estimate_households)
  )</code></pre>
<pre><code>## New names:
## Rows: 831 Columns: 123
## ── Column specification
## ──────────────────────────────────────────────────────── Delimiter: &quot;,&quot; chr
## (83): Geography, Geographic Area Name, Total!!Estimate!!Households!!One ... dbl
## (39): Total!!Estimate!!Households, Total!!Margin of Error!!Households, M... lgl
## (1): ...123
## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
## Specify the column types or set `show_col_types = FALSE` to quiet this message.
## • `` -&gt; `...123`</code></pre>
<pre class="r"><code>income_state &lt;- bind_rows(inc15, inc16)</code></pre>
</div>
<div id="income-by-state" class="section level3">
<h3>income by state</h3>
<pre class="r"><code>income_state_with_state &lt;- income_state |&gt;
  mutate(
    state = str_squish(str_extract(state_name, &quot;[^,]+$&quot;)))

income_state_level &lt;- income_state_with_state |&gt;
  group_by(year, state) |&gt;
  summarise(
    n_counties = n(),
    median_income_state = median(median_income, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

income_state_level &lt;- income_state_with_state |&gt;
  group_by(year, state) |&gt;
  summarise(
    n_counties = n(),
    median_state = median(median_income, na.rm = TRUE),
    mean_state   = mean(median_income, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

income_state_level |&gt; head(10)</code></pre>
<pre><code>## # A tibble: 10 × 5
##     year state                n_counties median_state mean_state
##    &lt;dbl&gt; &lt;chr&gt;                     &lt;int&gt;        &lt;dbl&gt;      &lt;dbl&gt;
##  1  2015 Alabama                      21       43553      46460.
##  2  2015 Alaska                        3       76427      76021.
##  3  2015 Arizona                      10       45195      44712.
##  4  2015 Arkansas                     11       46070      45950.
##  5  2015 California                   40       58954      62095.
##  6  2015 Colorado                     12       65960.     67584.
##  7  2015 Connecticut                   8       70144.     72854.
##  8  2015 Delaware                      3       56778      59366.
##  9  2015 District of Columbia          1       75628      75628 
## 10  2015 Florida                      40       49466.     49624.</code></pre>
<p>As the Healthy Aging dataset is designed to monitor cognitive health
in older adults and Alzheimer’s disease primarily affects seniors, we
restricted our analytic sample to respondents aged 65+ years. For the
main state-level analysis, we used sex-grouped estimates labeled
“Overall” rather than sex-specific values so that each state–year
contributed a single prevalence estimate, simplifying the comparison
with state-level income and avoiding multiple correlated observations
per state.</p>
<pre class="r"><code>state_vec &lt;- unique(income_state_level$state)

az_cog_65_overall_state &lt;- az_cog_65_overall |&gt;
  filter(
    year_start %in% c(2015, 2016),
    sex_group == &quot;Overall&quot;,
    location_desc %in% state_vec
  )

az_income &lt;- az_cog_65_overall_state |&gt;
  left_join(
    income_state_level,
    by = c(&quot;year_start&quot; = &quot;year&quot;,
           &quot;location_desc&quot; = &quot;state&quot;)
  )</code></pre>
</div>
<div id="relationship" class="section level3">
<h3>relationship</h3>
<pre class="r"><code>ggplot(az_income,
       aes(x = median_state, y = data_value,
           color = factor(year_start))) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = FALSE) +
  labs(
    x = &quot;State-level median household income (USD)&quot;,
    y = &quot;Alzheimer’s-related cognitive prevalence (%)&quot;,
    color = &quot;Year&quot;,
    title = &quot;State-level cognitive burden vs income among adults 65+ (2015–2016)&quot;
  )</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/unnamed-chunk-17-1.png" width="90%" /></p>
<pre class="r"><code>model_inc &lt;- lm(
  data_value ~ median_state + factor(year_start),
  data = az_income
)

summary(model_inc)</code></pre>
<pre><code>## 
## Call:
## lm(formula = data_value ~ median_state + factor(year_start), 
##     data = az_income)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -26.243 -12.189  -1.897   9.829  35.404 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             3.805e+01  3.260e+00  11.672  &lt; 2e-16 ***
## median_state           -2.354e-04  5.762e-05  -4.085 5.25e-05 ***
## factor(year_start)2016 -2.920e-01  1.723e+00  -0.169    0.866    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.32 on 431 degrees of freedom
## Multiple R-squared:  0.03882,    Adjusted R-squared:  0.03436 
## F-statistic: 8.704 on 2 and 431 DF,  p-value: 0.0001968</code></pre>
<p>In a linear regression of state-level Alzheimer’s-related cognitive
prevalence on median household income and survey year, higher income was
associated with lower cognitive burden. The estimated coefficient for
income was <span class="math inline">\(\hat\beta_{\text{income}} = -2.35
\times 10^{-4}\)</span>, meaning that a $1000 increase in state median
income was associated with about a prevalence, and a $10000 increase was
associated with about a prevalence among adults aged 65+. The
coefficient for survey year (2016 vs 2015) was small (<span
class="math inline">\(\hat\beta = -0.29\)</span>), suggesting no clear
overall difference between the two years after accounting for income.
However, the model <span class="math inline">\(R^2\)</span> was only ,
indicating that income explains only a small fraction of the large
between-state variation in cognitive outcomes.</p>
<p>Although higher state-level income was statistically associated with
lower Alzheimer’s-related cognitive prevalence, income explained only a
small share of the between-state variability. Several factors may
contribute to this weak relationship. First, the analysis is ecological:
each observation is an aggregated state–year estimate, so large
within-state differences in income and cognitive health are not
captured, and any individual-level association is diluted. Second, both
cognitive burden and income are measured with error (self-reported
survey indicators and ACS estimates), and we further aggregated
county-level income up to the state level, which may introduce
additional noise. Third, we only examined two years (2015–2016), over
which variation in both income and prevalence is fairly modest. Finally,
many other state-level determinants—such as education, health care
access, demographic composition, and prevalence of vascular risk
factors—were not adjusted for, so income alone is unlikely to account
for the wide variation in cognitive outcomes across states.</p>
</div>
</div>
<div id="education-effects" class="section level2">
<h2>Education Effects</h2>
<div id="data-import-2" class="section level3">
<h3>data import</h3>
<pre class="r"><code>edu15_raw &lt;- read_csv(&quot;data/education2015.csv&quot;, skip = 1) |&gt;
  janitor::clean_names()</code></pre>
<pre><code>## New names:
## Rows: 882 Columns: 771
## ── Column specification
## ──────────────────────────────────────────────────────── Delimiter: &quot;,&quot; chr
## (424): Geography, Geographic Area Name, Total!!Margin of Error!!Populati... dbl
## (346): Total!!Estimate!!Population 18 to 24 years, Males!!Estimate!!Popu... lgl
## (1): ...771
## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
## Specify the column types or set `show_col_types = FALSE` to quiet this message.
## • `` -&gt; `...771`</code></pre>
<pre class="r"><code>edu15_state &lt;- edu15_raw |&gt;
  filter(!str_detect(geographic_area_name, &quot;,&quot;))

edu16_raw &lt;- read_csv(&quot;data/education2016.csv&quot;, skip = 1) |&gt;
  janitor::clean_names()</code></pre>
<pre><code>## New names:
## Rows: 883 Columns: 771
## ── Column specification
## ──────────────────────────────────────────────────────── Delimiter: &quot;,&quot; chr
## (428): Geography, Geographic Area Name, Total!!Margin of Error!!Populati... dbl
## (342): Total!!Estimate!!Population 18 to 24 years, Males!!Estimate!!Popu... lgl
## (1): ...771
## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
## Specify the column types or set `show_col_types = FALSE` to quiet this message.
## • `` -&gt; `...771`</code></pre>
<pre class="r"><code>edu16_state &lt;- edu16_raw |&gt;
  filter(!str_detect(geographic_area_name, &quot;,&quot;))</code></pre>
<p>We used the proportion of adults aged 25 years and older with a
bachelor’s degree or higher as our main education indicator. This
measure is commonly reported in the ACS and captures individuals who
have completed at least a four-year college education, which is often
used as a marker of higher socioeconomic status and cognitive reserve in
the literature. Compared with more detailed education categories, using
“bachelor’s degree or higher” gives a simple, comparable summary of
educational attainment across states and years.</p>
<pre class="r"><code>edu15_state_slim &lt;- edu15_state |&gt;
  transmute(
    year = 2015,
    state = geographic_area_name,
    educ_bach = as.numeric(percent_estimate_percent_bachelors_degree_or_higher)
  )

edu16_state_slim &lt;- edu16_state |&gt;
  transmute(
    year = 2016,
    state = geographic_area_name,
    educ_bach = as.numeric(percent_estimate_percent_bachelors_degree_or_higher)
  )

edu_state &lt;- bind_rows(edu15_state_slim, edu16_state_slim)</code></pre>
<pre class="r"><code>az_edu &lt;- az_cog_65_overall_state |&gt;
  left_join(
    edu_state,
    by = c(
      &quot;year_start&quot; = &quot;year&quot;,
      &quot;location_desc&quot; = &quot;state&quot;
    ))</code></pre>
</div>
<div id="relationship-analysis" class="section level3">
<h3>relationship analysis</h3>
<pre class="r"><code>ggplot(az_edu,
       aes(x = educ_bach,
           y = data_value,
           color = factor(year_start))) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;, se = FALSE) +
  labs(
    x = &quot;State-level % with bachelor’s degree or higher (25+)&quot;,
    y = &quot;Alzheimer’s-related cognitive prevalence (%)&quot;,
    color = &quot;Year&quot;,
    title = &quot;State-level cognitive burden vs education among adults 65+ (2015–2016)&quot;
  ) +
  theme_minimal()</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/unnamed-chunk-22-1.png" width="90%" /></p>
<pre class="r"><code>model_edu &lt;- 
  lm(
  data_value ~ educ_bach + factor(year_start),
  data = az_edu)

summary(model_edu)</code></pre>
<pre><code>## 
## Call:
## lm(formula = data_value ~ educ_bach + factor(year_start), data = az_edu)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -19.554 -12.737  -2.077  10.376  39.346 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            29.87275    2.95268  10.117   &lt;2e-16 ***
## educ_bach              -0.16205    0.09617  -1.685   0.0927 .  
## factor(year_start)2016 -1.13543    1.73643  -0.654   0.5135    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.53 on 431 degrees of freedom
## Multiple R-squared:  0.008142,   Adjusted R-squared:  0.003539 
## F-statistic: 1.769 on 2 and 431 DF,  p-value: 0.1717</code></pre>
<p>In a linear regression of state-level Alzheimer’s-related cognitive
prevalence on the percentage of adults with a bachelor’s degree or
higher and survey year, higher education was associated with lower
cognitive burden. The estimated coefficient for education was <span
class="math inline">\(\hat\beta_{\text{educ}} = -0.16\)</span>, meaning
that a 1–percentage-point increase in the share of adults 25 years and
older with at least a bachelor’s degree was associated with about a
prevalence of Alzheimer’s-related cognitive problems among adults aged
65+. A 10–percentage-point increase in educational attainment would
correspond to roughly a prevalence. However, this association was
relatively weak and not conventionally statistically significant (the
approximate 95% confidence interval for <span
class="math inline">\(\hat\beta_{\text{educ}}\)</span> ranges from about
<span class="math inline">\(-0.35\)</span> to <span
class="math inline">\(0.03\)</span>). The coefficient for survey year
(2016 vs 2015) was small (<span class="math inline">\(\hat\beta =
-1.14\)</span>), suggesting no clear overall difference between the two
years after accounting for education. The model <span
class="math inline">\(R^2\)</span> was only about , indicating that
education and year together explain only a small fraction of the large
between-state variation in cognitive outcomes.</p>
<p>Although states with higher levels of college education tended to
have slightly lower Alzheimer’s-related cognitive prevalence, the
relationship was weak and most of the between-state variability remained
unexplained. Several factors may help explain this. First, the analysis
is ecological: each data point is a state–year average, so big
within-state differences in education and cognitive health are smoothed
out, and any individual-level association is likely diluted. Second,
both education and cognitive burden come from survey-based estimates and
can be measured with error; on top of that, we aggregated county-level
education indicators to the state level, which probably adds extra
noise. Third, we only looked at two survey years (2015–2016), so there
is not much variation over time in either education or cognitive
outcomes. Finally, many other state-level factors—such as income, access
to health care, population structure, and the prevalence of vascular and
lifestyle risk factors—were not included in the model, so education
alone is unlikely to explain the wide differences in cognitive outcomes
across states.</p>
</div>
</div>
<div id="alzheimers-outcomes-at-state-year-level"
class="section level2">
<h2>Alzheimer’s outcomes at state-year level</h2>
<pre class="r"><code>az_state_year &lt;- az_cog_65_overall |&gt;
  filter(
    year_start %in% c(2015, 2016),
    sex_group == &quot;Overall&quot;
  ) |&gt;
  group_by(
    year       = year_start,
    state_abbr = location_abbr,
    state_name = location_desc
  ) |&gt;
  summarise(
    mean_prev = mean(data_value, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

head(az_state_year)</code></pre>
<pre><code>## # A tibble: 6 × 4
##    year state_abbr state_name           mean_prev
##   &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;                    &lt;dbl&gt;
## 1  2015 AL         Alabama                   30.2
## 2  2015 AR         Arkansas                  27.6
## 3  2015 AZ         Arizona                   23.4
## 4  2015 CA         California                25.7
## 5  2015 CO         Colorado                  22.8
## 6  2015 DC         District of Columbia      30.3</code></pre>
</div>
<div id="air-pollution-effects" class="section level2">
<h2>Air Pollution Effects</h2>
<div id="data-import-3" class="section level3">
<h3>Data import</h3>
<pre class="r"><code>air15 &lt;- read_csv(&quot;data/clean_air_state_2015.csv&quot;)</code></pre>
<pre><code>## Rows: 52 Columns: 5
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (2): state_abbr, state_desc
## dbl (3): n_counties, pm25_wtd_mean, year
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>air16 &lt;- read_csv(&quot;data/clean_air_state_2016.csv&quot;)</code></pre>
<pre><code>## Rows: 52 Columns: 5
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (2): state_abbr, state_desc
## dbl (3): n_counties, pm25_wtd_mean, year
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>air_state &lt;- bind_rows(air15, air16)

air_state |&gt; head()</code></pre>
<pre><code>## # A tibble: 6 × 5
##   state_abbr state_desc n_counties pm25_wtd_mean  year
##   &lt;chr&gt;      &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
## 1 AK         Alaska              5         10.3   2015
## 2 AL         Alabama            18          9.02  2015
## 3 AR         Arkansas           11          8.82  2015
## 4 AZ         Arizona            13          7.7   2015
## 5 CA         California         51          9.83  2015
## 6 CO         Colorado           26          6.38  2015</code></pre>
<p>We used state-level fine particulate matter (PM2.5) concentrations as
our primary indicator of air pollution. Specifically, we relied on the
24-hour weighted mean PM2.5 values derived from EPA AirData annual
summary reports. These data were originally reported at the county level
and then aggregated to obtain state–year averages for 2015 and 2016,
matching the years available in the CDC Healthy Aging cognitive
dataset.</p>
<pre class="r"><code>air_state_level &lt;- air_state |&gt;
  group_by(year, state_abbr) |&gt;
  summarise(
    pm25_state = mean(pm25_wtd_mean, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

air_state_level |&gt; head(10)</code></pre>
<pre><code>## # A tibble: 10 × 3
##     year state_abbr pm25_state
##    &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt;
##  1  2015 AK              10.3 
##  2  2015 AL               9.02
##  3  2015 AR               8.82
##  4  2015 AZ               7.7 
##  5  2015 CA               9.83
##  6  2015 CO               6.38
##  7  2015 CT               8.1 
##  8  2015 DE               8.57
##  9  2015 FL               6.54
## 10  2015 GA               9.02</code></pre>
</div>
<div id="merge-with-alzheimers-outcomes" class="section level3">
<h3>merge with Alzheimer’s outcomes</h3>
<pre class="r"><code>az_cog_65_overall_state &lt;- az_cog_65_overall |&gt;
  filter(
    year_start %in% c(2015, 2016),
    sex_group == &quot;Overall&quot;
  )

az_air &lt;- az_cog_65_overall_state |&gt;
  left_join(
    air_state_level,
    by = c(
      &quot;year_start&quot;    = &quot;year&quot;,
      &quot;location_abbr&quot; = &quot;state_abbr&quot;
    )
  )

az_air |&gt;
  select(year_start, location_desc, pm25_state, data_value) |&gt;
  head(10)</code></pre>
<pre><code>##    year_start        location_desc pm25_state data_value
## 1        2015 District of Columbia         NA       46.4
## 2        2015              Alabama   9.021429       36.8
## 3        2015             Colorado   6.377778       19.6
## 4        2015              Alabama   9.021429       12.5
## 5        2015              Georgia   9.025000       37.5
## 6        2015               Hawaii   6.725000       15.1
## 7        2015                 Iowa   8.415385        9.8
## 8        2015             Colorado   6.377778       10.5
## 9        2015              Alabama   9.021429       33.4
## 10       2015              Arizona   7.700000       20.7</code></pre>
<p>For consistency with the income and education analyses, we restricted
the sample to adults aged 65+ years and used the sex-grouped estimates
labeled “Overall”. Each state–year therefore contributes a single
Alzheimer’s-related prevalence value, which we then merged with the
corresponding state–year PM2.5 concentration.</p>
</div>
<div id="relationship-analysis-1" class="section level3">
<h3>relationship analysis</h3>
<pre class="r"><code>ggplot(az_air,
       aes(x = pm25_state,
           y = data_value, 
           color = factor(year_start))) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;, se = FALSE) +
  labs(
    x = &quot;State-level PM2.5 weighted mean (µg/m³)&quot;,
    y = &quot;Alzheimer’s-related cognitive prevalence (%)&quot;,
    color = &quot;Year&quot;,
    title = &quot;State-level cognitive burden vs PM2.5 among adults 65+ (2015–2016)&quot;
  ) +
  theme_minimal()</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 187 rows containing non-finite outside the scale range
## (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 187 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/unnamed-chunk-28-1.png" width="90%" /></p>
<pre class="r"><code>model_air &lt;- lm(
  data_value ~ pm25_state + factor(year_start),
  data = az_air
)

summary(model_air)</code></pre>
<pre><code>## 
## Call:
## lm(formula = data_value ~ pm25_state + factor(year_start), data = az_air)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -18.972 -12.651  -2.391  10.294  39.928 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             26.5460     4.4889   5.914 6.95e-09 ***
## pm25_state              -0.2067     0.5494  -0.376    0.707    
## factor(year_start)2016  -1.1602     1.7507  -0.663    0.508    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.49 on 419 degrees of freedom
##   (187 observations deleted due to missingness)
## Multiple R-squared:  0.001254,   Adjusted R-squared:  -0.003514 
## F-statistic: 0.263 on 2 and 419 DF,  p-value: 0.7689</code></pre>
<p>In a linear regression of state-level Alzheimer’s-related cognitive
prevalence on PM2.5 and survey year, we did not observe a clear
association between air pollution and cognitive burden among adults aged
65+. The estimated coefficient for PM2.5 was <span
class="math inline">\(\hat\beta_{\text{PM2.5}} =\)</span> -0.207,
meaning that a 1–µg/m³ increase in the state-level PM2.5 weighted mean
was associated with an estimated -0.207–percentage-point change in
Alzheimer’s-related cognitive prevalence. A 10–µg/m³ difference in PM2.5
would therefore correspond to roughly -2.07 percentage points. However,
this association was small and not statistically significant (p =
0.707), indicating that PM2.5 is not a strong predictor of between-state
differences in cognitive burden in this model.</p>
<p>The coefficient for survey year (2016 vs 2015) was <span
class="math inline">\(\hat\beta_{\text{year}} =\)</span> -1.16 with p =
0.508, suggesting no meaningful overall change in prevalence between the
two years after accounting for PM2.5. The model <span
class="math inline">\(R^2\)</span> was only 0.001, implying that PM2.5
and year together explain only a negligible fraction of the substantial
between-state variation in Alzheimer’s-related cognitive outcomes. This
is not surprising given the ecological nature of the analysis
(state-level averages), potential measurement error in both pollution
and cognitive indicators, the short two-year time window, and the
absence of other important determinants such as income, education,
demographics, and health care access.</p>
</div>
</div>
<div id="mapping-alzheimers-related-cognitive-burden"
class="section level2">
<h2>Mapping Alzheimer’s-related Cognitive Burden</h2>
<div id="state-level-choropleth-map-for-2015" class="section level3">
<h3>State-level choropleth map for 2015</h3>
<pre class="r"><code>library(maps)
library(stringr)

az_2015 = az_state_year |&gt; 
  filter(year == 2015)

us_map = map_data(&quot;state&quot;) |&gt; as_tibble()

az_map_2015 = az_2015 |&gt; 
  mutate(region = str_to_lower(state_name)) |&gt; 
  inner_join(us_map, by = &quot;region&quot;)

ggplot(az_map_2015,
       aes(long, lat, group = group, fill = mean_prev)) +
  geom_polygon(color = &quot;white&quot;, linewidth = 0.2) +
  coord_fixed(1.3) +
  scale_fill_viridis_c(option = &quot;C&quot;) +
  labs(
    title = &quot;Alzheimer’s-related cognitive prevalence (Age 65+, 2015)&quot;,
    fill  = &quot;Prevalence (%)&quot;
  ) +
  theme_void() +
  theme(legend.position = &quot;right&quot;)</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/map_2015-1.png" width="90%" /></p>
</div>
<div id="state-level-choropleth-map-for-2016" class="section level3">
<h3>State-level choropleth map for 2016</h3>
<pre class="r"><code>library(maps)
library(stringr)

az_2016 = az_state_year |&gt; 
  filter(year == 2016)

us_map = map_data(&quot;state&quot;) |&gt; as_tibble()

az_map_2016 = az_2016 |&gt; 
  mutate(region = str_to_lower(state_name)) |&gt; 
  inner_join(us_map, by = &quot;region&quot;)

ggplot(az_map_2016,
       aes(long, lat, group = group, fill = mean_prev)) +
  geom_polygon(color = &quot;white&quot;, linewidth = 0.2) +
  coord_fixed(1.3) +
  scale_fill_viridis_c(option = &quot;C&quot;) +
  labs(
    title = &quot;Alzheimer’s-related cognitive prevalence (Age 65+, 2016)&quot;,
    fill  = &quot;Prevalence (%)&quot;
  ) +
  theme_void() +
  theme(legend.position = &quot;right&quot;)</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/map_2016-1.png" width="90%" /></p>
</div>
<div id="side-by-side-comparison-2015-vs-2016" class="section level3">
<h3>Side-by-side Comparison (2015 vs 2016)</h3>
<pre class="r"><code>az_15_16 = az_state_year |&gt; 
  filter(year %in% c(2015, 2016))

us_map = map_data(&quot;state&quot;) |&gt; as_tibble()

az_map_15_16 = az_15_16 |&gt; 
  mutate(region = str_to_lower(state_name)) |&gt; 
  inner_join(us_map, by = &quot;region&quot;)

ggplot(az_map_15_16,
       aes(long, lat, group = group, fill = mean_prev)) +
  geom_polygon(color = &quot;white&quot;, linewidth = 0.2) +
  coord_fixed(1.3) +
  scale_fill_viridis_c(option = &quot;C&quot;) +
  labs(
    title = &quot;Alzheimer’s-related cognitive prevalence (Age 65+, 2015–2016)&quot;,
    fill  = &quot;Prevalence (%)&quot;
  ) +
  theme_void() +
  theme(legend.position = &quot;right&quot;) +
  facet_wrap(~ year)</code></pre>
<p><img src="P8105_final_Alzheimei_files/figure-html/map_compare_2015_2016-1.png" width="90%" /></p>
<p>Geographic patterns of Alzheimer’s-related cognitive prevalence were
visualized using state-level choropleth maps for 2015 and 2016. In both
years, several Southern and Southeastern states showed higher prevalence
levels, while many Western and Northeastern states displayed noticeably
lower burdens. The spatial distribution remained largely consistent
between 2015 and 2016, suggesting limited short-term change in
geographic patterns of cognitive burden among adults aged 65+.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
